FROM ubuntu:14.04

# Use commands as little as possible to reduce the image size


# Copy app sources
# add the last slash to make the folder and copy the file into the folder.
# Otherwise, it recognizes that as a file and creates the webpack-react-example file
# COPY ./.babelrc /webpack-react-example/
# COPY ./.eslintrc /webpack-react-example/
# COPY ./gulpfile.babel.js /webpack-react-example/
# COPY ./npm-shrinkwrap.json /webpack-react-example/
# COPY ./npm-shrinkwrap.prod.json /webpack-react-example/
# COPY ./package.json /webpack-react-example/
# COPY ./webpack.config.js /webpack-react-example/

# COPY ["./.babelrc", "./.eslintrc", "./gulpfile.babel.js", "./npm-shrinkwrap.json", "./npm-shrinkwrap.prod.json",
#       "./package.json", "./webpack.config.js", "/webpack-react-example/"]

# COPY ./client /webpack-react-example/client
# COPY ./react-html-generator /webpack-react-example/react-html-generator
# COPY ./server /webpack-react-example/server
# COPY ./test /webpack-react-example/test

# to reduce the image size by using just a COPY command
COPY ./ /webpack-react-example/


# sudo apt-get update => downloads the package lists from the repositories and "updates" them to get information
# --fix-missing => to fix problems in the installation
# rm /bin/sh && ln -s /bin/bash /bin/sh => Replace shell with bash so we can source files
# curl -o- https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh | bash => Install NVM

# @ to build some npm modules
# Install Python
# sudo apt-get -y install build-essential => Install make and gcc
# sudo apt-get -y install libkrb5-dev => for kerberos that is one of mongodb's sub-modules
# sudo apt-get -y install libpq-dev => for pq
# sudo apt-get -y install libfontconfig => phantomjs
# to build some npm modules @

# @ for e2e test
# sudo apt-get -y install openjdk-7-jdk => selenium
# for e2e test @
RUN sudo apt-get update --fix-missing && \
    apt-get -y install curl && \
    rm /bin/sh && ln -s /bin/bash /bin/sh && \
    export NVM_VERSION=v0.31.0 && \
    curl -o- https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh | bash && \
    sudo apt-get -y install python2.7 && \
    ln -s /usr/bin/python2.7 /usr/bin/python && \
    sudo apt-get -y install build-essential && \
    sudo apt-get -y install libpq-dev && \
    sudo apt-get -y install libfontconfig && \
    sudo apt-get -y install openjdk-7-jdk && \
    sudo apt-get -y install firefox && \
    sudo apt-get -y install xvfb


# source ~/.nvm/nvm.sh; ==> to use nvm and install Node
RUN export NODE_VERSION=v4.2.4 && \
    source ~/.nvm/nvm.sh && \
    nvm install $NODE_VERSION && \
    cd /webpack-react-example && \
    npm install -g gulp@3.9.1 && \
    npm install && \
    gulp prod-build


# CMD ["executable", "param1", "param2"]
CMD source ~/.nvm/nvm.sh && \
    cd /webpack-react-example && \
    node ./node_modules/pm2/bin/pm2 start ./server/index.js -i 4 --no-daemon
