export const ADD_TODO = 'ADD_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const SET_EDITING_STATUS = 'SET_EDITING_STATUS';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const DELETE_TODO = 'DELETE_TODO';

export const REPLACE_TODOS = 'REPLACE_TODOS';

export default {
  ADD_TODO,
  COMPLETE_ALL,
  CLEAR_COMPLETED,

  SET_EDITING_STATUS,
  EDIT_TODO,
  COMPLETE_TODO,
  DELETE_TODO,

  REPLACE_TODOS
};
